### ISSUE TITLE
The font script doesn't load properly on github

### ISSUE THREAD

**Issue by Shadowblitz16** [raylib-extras/rlImGui-cs#11]
this doesn't load properly on github.
https://github.com/raylib-extras/rlImGui-cs/blob/main/rlImGui/IconsFontAwesome6.cs

**Comment by JeffM2501** [comment]
I've moved the font data over to it's own file. Nobody should ever have to open or edit it. I don't expect the fact that some editors don't do word wrap to affect the usefulness of the feature.
