### ISSUE TITLE
Method not found

### ISSUE THREAD

**Issue by FormalSnake** [raylib-extras/rlImGui-cs#12]
```
Unhandled exception. System.MissingMethodException: Method not found: 'ImGuiNET.RangePtrAccessor`1<ImGuiNET.ImDrawListPtr> ImGuiNET.ImDrawDataPtr.get_CmdListsRange()
'.
   at rlImGui_cs.rlImGui.RenderData()
   at rlImGui_cs.rlImGui.End()
   at HelloWorld.Program.Main() in /Users/kyandesutter/development/formal-engine-rewrite/Program.cs:line 156

```
https://github.com/FormalSnake/formal-engine/tree/rewrite

**Comment by FormalSnake** [comment]
I am on macOS sonoma

**Comment by JeffM2501** [comment]
sounds like a mismatch with ImGui.net. what version of that package are you using?

**Comment by FormalSnake** [comment]
It does indeed, this is my package list
```xml
<PackageReference Include="Raylib-cs" Version="4.5.0.4" />
<PackageReference Include="ImGui.NET" Version="1.89.9.2" />
<PackageReference Include="rlImgui-cs" Version="1.0.2" />
```

**Comment by FormalSnake** [comment]
This commit in ImGUI.NET might help
https://github.com/ImGuiNET/ImGui.NET/pull/427/commits/ab3011592e412aeca489b1e5485b5dad340e8bd6

**Comment by FormalSnake** [comment]
So I downgraded to try it, the program launches but I do not see a demo window, but it does create the .ini file.
<img width="1392" alt="Screenshot 2023-09-28 at 17 11 27" src="https://github.com/raylib-extras/rlImGui-cs/assets/90651091/0b2a1015-987a-4b5b-be2e-50f3a78fb7c8">
<img width="1768" alt="Screenshot 2023-09-28 at 17 11 40" src="https://github.com/raylib-extras/rlImGui-cs/assets/90651091/376c4cae-c4c8-44cb-8c75-7a66967f240b">

**Comment by FormalSnake** [comment]
<img width="1392" alt="Screenshot 2023-09-28 at 17 21 37" src="https://github.com/raylib-extras/rlImGui-cs/assets/90651091/536c17b4-4368-4ebf-a230-0b5166c0599c">
this is what the sample app looks like

**Comment by JeffM2501** [comment]
Yes, ImGui.net updated the package and made it incompatible with the code in rlImGui. rlImGui was meant to use a specific version of ImGui.Net.
I have updated the package and code that this repository issues, so it should be compatible now with the current ImGui.net version

**Comment by FormalSnake** [comment]
sadly, i am having this problem
https://github.com/raylib-extras/rlImGui-cs/issues/6
the M1 GPU. not sure if this can be fixed rn
