### ISSUE TITLE
Missing text and box when maximizing window + fullscreen

### ISSUE THREAD

**Issue by Magnatales** [raylib-extras/rlImGui-cs#13]
**Problem:**
When using rlImGui and using `Raylib.MaximizeWindow();` and `Raylib.ToggleFullscreen();` there are some text missing in imgui.

**Setup:**
```
rlImGui.Setup();
public override void Draw()
    {
        rlImGui.Begin();
        ImGui.ShowDemoWindow();
        rlImGui.End();
    }

public override void Update()
    {
        if (Raylib.IsKeyPressed(KeyboardKey.KEY_F11))
        {
           Raylib.MaximizeWindow();
           Raylib.ToggleFullscreen();
        }
    }
```
**Showcase:**

https://github.com/raylib-extras/rlImGui-cs/assets/72097037/622c19af-a70c-4f18-aaa1-8ca6984fbc22

**Note:**
This **does not happen** when only using `Raylib.ToggleFullscreen();` so it's an issue related when using fullscreen in a window that is maximized.

**Comment by JeffM2501** [comment]
Can you provide a complete example program that shows the problem and let me know what platform you are on?

**Comment by Guillemsc** [comment]
I could also reproduce. You just need maximize a window, and then set fullscreen to it with   `Raylib.SetWindowState(ConfigFlags.FLAG_FULLSCREEN_MODE);`. Part of all the imgui windows does not show.
If the window is not maximised when going fullscreen, the issue does not happen.
Tried on version 1.0.2 and 2.0.0, on Windows 10.

Windowed:
![image](https://github.com/raylib-extras/rlImGui-cs/assets/17142208/98e75448-9c37-4c28-8d5c-05ac055fda9e)

Fullscreen:
![image](https://github.com/raylib-extras/rlImGui-cs/assets/17142208/36f96b0d-8f81-4892-be4a-9ba7b8f943fa)

**Comment by JeffM2501** [comment]
I found the problem, it was in both the C++ and C# versions of rlImGui and has been fixed in both places. Thank you for the report.
