### ISSUE TITLE
MissingFieldException

### ISSUE THREAD

**Issue by Shadowblitz16** [raylib-extras/rlImGui-cs#14]
![image](https://github.com/raylib-extras/rlImGui-cs/assets/2453707/03f341d6-2f2f-4b2e-b350-4daed87dc3cd)
I am using the nuget version
![image](https://github.com/raylib-extras/rlImGui-cs/assets/2453707/6149b9e9-a568-4ed6-adf1-17f118c60cfc)

**Comment by JeffM2501** [comment]
My guess is there is some issue with the native runtimes for Raylib-cs on your platform ,make sure the native DLLs are 4.5. But this is not an issue with rlImGui itself.

**Comment by Shadowblitz16** [comment]
> My guess is there is some issue with the native runtimes for Raylib-cs on your platform ,make sure the native DLLs are 4.5. But this is not an issue with rlImGui itself.

Does raylib-cs not install native binaries through nuget?

**Comment by JeffM2501** [comment]
I don't know, rlImgui just links to the package.

**Comment by MaximilianMcC** [comment]
I'm also getting the same issue in my project. To test, I directly coppied the example and tried to run that, however it gave the same issue. This is what my `.csproj` looks like:
```csproj
<ItemGroup>
  <PackageReference Include="ImGui.NET" Version="1.89.9.3" />
  <PackageReference Include="Raylib-cs" Version="5.0.0" />
  <PackageReference Include="rlImgui-cs" Version="1.0.3" />
</ItemGroup>
```
When running I get
 `An unhandled exception of type 'System.MissingFieldException' occurred in map-editor.dll: 'Field not found: 'Raylib_cs.Texture2D.id'.'`

**Comment by JeffM2501** [comment]
This makes no sense.
Raylib 5.0 is not out yet, thus there can not be a raylib-cs bindiding for it.

The nuget package for rlImGui-cs uses raylib-cs 4.5.0.4
![image](https://github.com/raylib-extras/rlImGui-cs/assets/322174/8f1ba3f3-5865-45cf-8848-2406acf7ddd9)

as do the projects that are checked in

![image](https://github.com/raylib-extras/rlImGui-cs/assets/322174/988124a4-0548-4d49-b205-aaaa4e8fade0)
![image](https://github.com/raylib-extras/rlImGui-cs/assets/322174/2f624068-0c9d-41ac-bf85-1357b258631a)
![image](https://github.com/raylib-extras/rlImGui-cs/assets/322174/380aad46-f1cb-4c0b-ae0b-771fad94a8b7)

So I have no clue how you got a 5.0 in there, but that is just wrong.

**Comment by MaximilianMcC** [comment]
I got RayLib from a VScode extension that I use to search for Nuget packages. I know that RayLib 5 is very close to being finished, so I just assumed that it was out. I'm not sure how that got in there. Running the RayLib 5 also works for some reason. I guess someone might have updated the number in anticipation?
![image](https://github.com/raylib-extras/rlImGui-cs/assets/93854112/60988f5b-5f68-48f7-8412-00487e71833e)
Anyways, I downgraded to `4.5.0.4` and it works. Thanks for the help. This is now my new `.csproj` file:
```csproj
<ItemGroup>
  <PackageReference Include="ImGui.NET" Version="1.89.9.3" />
  <PackageReference Include="Raylib-cs" Version="4.5.0.4" />
  <PackageReference Include="rlImgui-cs" Version="1.0.3" />
</ItemGroup>
```

**Comment by JeffM2501** [comment]
Raylib 5.0 has breaking changes, I will update and branch rlImGui-CS once it's fully released

**Comment by rgebee** [comment]
@JeffM2501 Raylib-cs 5.0.0 is still using raylib 4.5.0. This is because there are breaking changes I wanted to release before raylib 5.0 so I decided to move from following raylib versions directly to a separate version instead so I could make these type of changes clearer instead of only using a build number. I will update the extras repos soon to work with this release.

**Comment by JeffM2501** [comment]
> @JeffM2501 Raylib-cs 5.0.0 is still using raylib 4.5.0. This is because there are breaking changes I wanted to release before raylib 5.0 so I decided to move from following raylib versions directly to a separate version instead so I could make these type of changes clearer instead of only using a build number. I will update the extras repos soon to work with this release.

I have an updated version that works with raylib-cs 5.0.0.
Thanks for clearing it up.

**Comment by JeffM2501** [comment]
I have updated this codebase to work with raylib-cs 5.0.0 and made it dependent on it. A new nuget package has been made (2.0).
