### ISSUE TITLE
Problem with 'io.KeysData'

### ISSUE THREAD

**Issue by cos1110** [raylib-extras/rlImGui-cs#16]
For me this line crashes because there is an 'index out of range exception'.

```
foreach (var keyItr in RaylibKeyMap)
    io.KeysData[(int)keyItr.Value].Down = (byte)(Raylib.IsKeyDown(keyItr.Key) ? 1 : 0);
```

I figured that this is offset value is needed. It worked for me fine, text input is OK.
https://github.com/ocornut/imgui/blob/e265610a0c4143b9abc64c50a3950ddcd0243622/imgui.h#L1425
```

foreach (var keyItr in RaylibKeyMap)
	io.KeysData[(int)(keyItr.Value - ImGuiKey.KeysData_OFFSET)].Down = (byte)(Raylib.IsKeyDown(keyItr.Key) ? 1 : 0);

```

**Comment by JeffM2501** [comment]
That code is not needed and a holdover from the previous key input system. It has been removed.

**Comment by cos1110** [comment]
OK, it looks like you updated it. Thanks.
