### ISSUE TITLE
ImGui glitches when it is out of screen

### ISSUE THREAD

**Issue by tingspain** [raylib-extras/rlImGui-cs#21]
Hello, 

First of all, thank you for the your great job. Your project has been very useful for me. 

Now, going back to the matter, I have been testing your project and I found a weird behaviour of ImGui. When the window is place out side the screen on the left side, ImGui glitches. I have been checking your code but i dont find the issue. I have attached two videos showing the issue. 

Any idea what it could be happening?  

I am on macOS Sonoma 14.3.1 running on a M1 Max. 

**Test 1**

https://github.com/raylib-extras/rlImGui-cs/assets/1858083/6463fa5e-14c6-458b-9247-fdfc32080f07

**Test 2**

https://github.com/raylib-extras/rlImGui-cs/assets/1858083/651a6404-8dc5-45ab-a481-2a92d2c94bdd

**Comment by JeffM2501** [comment]
That looks like an OpenGL issue with the stencil buffer on the mac. There are known bugs with stencil and OpenGL in the mac video drivers.
There is nothing special that we do based on the window origin. I'm not sure that this is an issue that can be fixed at the rlImGui level.

Do you init your window with the high DPI flag enabled?

**Comment by tingspain** [comment]
I didn't enable high DPI. I just used your code as it is. But I tried to enable high DPI and the same issue. 

I implemented an ImGuiController following your code, as well as, I recreated your example project and the issue is gone. However, I implemented it using Raylib-CsLo and ImGui.net 1.87.3 (Instead of  1.90.1.1)

**Comment by JeffM2501** [comment]
Can you try to build this repo with ImGui 1.87.3 and see if it happens too? That will tell me if it's an issue with ImGui or some other issue.

**Comment by tingspain** [comment]
@JeffM2501 Give me a few days, and I will compile it using 1.87.3

**Comment by tingspain** [comment]
I compiled it with ImGui.NET v1.87.3 and Raylib-cs v6.0.0 and I got the same issue.  

I think the problem comes from Raylib-cs or Raylib itself. Raylib-cs is porting Raylib 5, while in the working version that I have, I am using Raylib-CsLo which is porting Raylib 4. 

@JeffM2501, Any suggestion? 

Thanks in advance

**Comment by JeffM2501** [comment]
Try it in C++ and see if it happens, if it's raylib it'd be in the C version too. But no mater what it seems out of scope for this library
