### ISSUE TITLE
Custom fonts entirely broken & can cause memory corruption

### ISSUE THREAD

**Issue by Nolram12345** [raylib-extras/rlImGui-cs#22]
I've been trying to get custom fonts working using rlImGui-cs for about 4 hours now - something that would take 20 seconds using C++ and ImGui - and I just can't figure it out.

I have tried:
1. Just as in C++, getting the IoPtr and loading the font from a TTF file. This does nothing. The font does not get used.
2. Doing 1, but then calling ReloadFonts. This does nothing.
3. Doing 2, but then using PushFont. This causes a memory corruption error and crashes.
4. Doing 1 & 2 in the InstallFonts callback.

None of these work. Do you have an functioning example of loading a custom font?

**Comment by JeffM2501** [comment]
Yes, you don't have to call reload fonts at all. you just need to insert your font call into the correct place in the startup order.

There is a callback (delegate) you can install in rlImGui to setup your own fonts. it's called by rlImGui before it loads the font atlas, and gives you a chance to install custom fonts in addition to the default font and font awesome.
```
                 ImFontPtr newFont = null;
                 rlImGui.SetupUserFonts = io => newFont = io.Fonts.AddFontFromFileTTF("resources/Kenney Future.ttf", 18);

                 rlImGui.Setup();
```
That will add a new font that you can push and pop with code like this.
```
                 ImGui.PushFont(newFont);
                 ImGui.TextUnformatted("New Font Text ");
                 ImGui.PopFont();
```

If you want to replace the default font, then you can do that by not using _rlImGui.Setup_, and instead using the sperate Begin/End Init functions and set your font before calling _EndInitImGui()_. This will set a font and prevent rlImGui from installing the default font and FontAwesome.

```
// do not call rlImGui.Setup(), call this instead.
            rlImGui.BeginInitImGui();
            ImGui.StyleColorsDark();
            ImGui.GetIO().Fonts.AddFontFromFileTTF("resources/Kenney Future.ttf", 18);
            rlImGui.EndInitImGui();
```
If you replace the default font with your own, you do not need to push and pop fonts.

**Comment by Nolram12345** [comment]
Oh my goodness thank you so much! I finally got it to work. I thought using rlImGui.Setup() was mandatory. Thank you!

**Comment by JeffM2501** [comment]
Setup is the simple setup and does a lot of automatic stuff, both the C# and C++ have the split setup for custom stuff.
