### ISSUE TITLE
Drawing bug...

### ISSUE THREAD

**Issue by Shadowblitz16** [raylib-extras/rlImGui-cs#25]
The blue focus highlight is bugged.
![image](https://github.com/user-attachments/assets/c15b18f6-0fd2-4859-a3f3-4f52e6d4e892)

**Comment by JeffM2501** [comment]
There is not enough info here to respond properly.

Please provide the code you are calling and what platform you are on.

**Comment by Shadowblitz16** [comment]
here is the code... https://github.com/Shadowblitz16/MarioKit

I am on kubuntu 22.04, Raylib-cs, C#, .NET 8.0

**Comment by JeffM2501** [comment]
Seems to work just fine for me.
Can you provide more detail about what is 'bugged'?
Please understand that we can't read your mind, and may not see the same results that you see. The more detail you can provide the better we can help. Something that may be obvious to you may not be obvious to others who have not been deep in your project.

![gui](https://github.com/user-attachments/assets/0231bef0-ed4e-498a-aa53-8c56870ac804)

**Comment by Shadowblitz16** [comment]
Its the blue outline on the outer top edge of the window when it's focused.
When I move it around it sometimes is larger on the left side

**Comment by JeffM2501** [comment]
That sounds like an OpenGL/driver issue on your end. rlImGui just passes the ImGui generated geometry to raylib and thus to OpenGL, it does not specifically pick what to draw where. I'd make sure your video driver is up to date.
There is no code I can change in rlImGui that would effect this.

**Comment by Shadowblitz16** [comment]
@JeffM2501 please reopen this I don't get this issue with silk.net's opengl and imgui.

<img width="173" height="95" alt="Image" src="https://github.com/user-attachments/assets/ed2d40e0-0a6d-4a1f-9f33-bafec5868bd3" />

It's an issue on how your passing the triangles.
If you can give me a c example to clone and compile and try I can see if it's c raylib's fault, but idk how to get c or c++ up and running, let alone link libraries to it.

```cs
using ImGuiNET;
using rlImGui_cs;

namespace EditorX.Editor;
using Raylib_cs;
public class Editor
{

    public void Run()
    {
        Raylib.InitWindow(800,600, "EditorX");
        Raylib.InitAudioDevice();

        rlImGui_cs.rlImGui.Setup(true, true);
        while (!Raylib.WindowShouldClose())
        {

            Raylib.BeginDrawing();
            Raylib.ClearBackground(Color.Black);
            rlImGui_cs.rlImGui.Begin(Raylib.GetFrameTime());

           OnGui();
            
            rlImGui_cs.rlImGui.End();
            Raylib.EndDrawing();
        }
        rlImGui_cs.rlImGui.Shutdown();
        
    }
    
    private void OnGui()
    {
        ImGui.DockSpaceOverViewport();

        SceneWindow();
    }


    private RenderTexture2D? _canvas;
    private void SceneWindow()
    {
        _canvas ??= Raylib.LoadRenderTexture(160, 144);
        
        ImGui.Begin("Scene Window");
        rlImGui.Image(_canvas.Value.Texture);
        ImGui.End();
    }
}
```

**Comment by JeffM2501** [comment]
I can't make an example just for you, you can look at the C/C++ examples in rlImGui
