### ISSUE TITLE
Is this repo still maintained?

### ISSUE THREAD

**Issue by fredtheking** [raylib-extras/rlImGui-cs#26]
Just noticed that RaylibCs 7.0.0 released, which is an upgrade to raylib 5.5 and i really wanted to use this library. For some strange reason, they changed all "Ready" functions to "Valid" (like "IsTextureValid" instead of "IsTextureReady"). I could potentially edit code and make a pull request, but im not sure ill get an acception. 

So i need an answer, is it still maintained or not?

**Comment by JeffM2501** [comment]
yeah, raylib-cs was only recently updated... 

I have updated this lib to the current raylib-cs an imgui nuget packages.

**Comment by fredtheking** [comment]
oh, thats great! thx!!
