### ISSUE TITLE
examples in macOS not correct showing

### ISSUE THREAD

**Issue by zhengying** [raylib-extras/rlImGui-cs#4]
MacOS 11.6 .net core 6.0

<img width="1023" alt="Screen Shot 2022-10-30 at 11 03 29 AM" src="https://user-images.githubusercontent.com/1042545/198860804-83487be4-d48d-4bc4-9807-baf061de15fb.png">
<img width="1278" alt="Screen Shot 2022-10-30 at 11 03 05 AM" src="https://user-images.githubusercontent.com/1042545/198860805-46e7e426-de9d-4ff5-9cac-f9300106568d.png">

**Comment by JeffM2501** [comment]
Yes, this is a known unfixable issue with MacOS and C#. The function needed to add in the workaround for this Mac specific problem it is not exposed via Raylib-CS  (A GLFW function)

Sadly it's not possible to make this work in C#, only C/C++ where it can access GLFW directly. MacOS's OpenGL driver requires a work around to scale the stencil buffer on high DPI displays, and without the workaround it just won't work properly. Apple has deprecated OpenGL so they will not be fixing any driver bugs.

**Comment by zhengying** [comment]
Thanks for your detailed information.

**Comment by Shadowblitz16** [comment]
@JeffM2501 you should make a issue on c raylib repo and have raysan expose the function

**Comment by JeffM2501** [comment]
The current system is using a rlgl call this seems to work
