### ISSUE TITLE
[Request] NuGet package

### ISSUE THREAD

**Issue by leftbones** [raylib-extras/rlImGui-cs#8]

**Comment by JeffM2501** [comment]
rlImGui-cs is a single C# file, it doesn't need a nuget package, that'd be silly. Just add the file to your project. You need raylib and ImGui anyway.

**Comment by JeffM2501** [comment]
I've changed my mind on this since rlImGui is now multiple files. A nuget package has been published. https://www.nuget.org/packages/rlImgui-cs
